name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on changes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run unit tests for v1
      - name: Run unit tests
        env:
          MODEL_VERSION: v1  # Default to v1
        run: |
          pytest tests/

      # Step 5: Save the v1 model as an artifact
      - name: Save model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-v1-artifact
          path: ./v1/
