name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on changes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Identify the latest model version
      - name: Identify latest model version
        id: latest_version
        run: |
          latest_version=$(ls -d ./v*/ | sort -r | head -n 1 | cut -d'/' -f1)
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV
        shell: bash

      # Run unit tests on the latest version
      - name: Run unit tests
        env:
          LATEST_VERSION: ${{ env.LATEST_VERSION }}
        run: |
          pytest tests/ --model-path $LATEST_VERSION

      # Save the latest model artifact
      - name: Save the latest model artifact
        uses: actions/upload-artifact@v3
        with:
          name: latest-model-artifact
          path: ${{ env.LATEST_VERSION }}/

      # Optional: Deploy the latest model
      - name: Deploy the latest model 
        run: |
          echo "Deploying model $LATEST_VERSION..."
          # Add your deployment logic here, e.g., upload to cloud, restart services, etc.
