name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on changes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run unit tests
      - name: Run unit tests
        run: |
          pytest tests/

      # Save the model artifact
      - name: Save model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-artifact
          path: ./v1/
